import { jsPDF } from 'jspdf'

/**
 * Generates a professional packing slip PDF for an order.
 * @param {Object} order - The order data object.
 */
export const generatePackingSlip = (order) => {
  const doc = new jsPDF()

  // Header
  doc.setFillColor(22, 22, 26) // var(--bg-accent) equivalent
  doc.rect(0, 0, 210, 40, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('Bluewud OTS', 15, 25)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Packing Slip', 160, 25)

  // Order Details Section
  doc.setTextColor(50, 50, 50)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('ORDER DETAILS', 15, 55)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Order ID: ${order.id}`, 15, 65)
  doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 15, 72)
  doc.text(`Status: ${order.status}`, 15, 79)

  // Customer Details
  doc.setFont('helvetica', 'bold')
  doc.text('SHIP TO', 120, 55)

  doc.setFont('helvetica', 'normal')
  doc.text(`${order.customer || 'Customer Name'}`, 120, 65)
  doc.text(`${order.city || 'City'}, ${order.state || 'State'}`, 120, 72)

  // SKU Line Item Table
  doc.setFont('helvetica', 'bold')
  doc.text('ITEMS', 15, 100)

  doc.setDrawColor(200, 200, 200)
  doc.line(15, 105, 195, 105)

  doc.setFont('helvetica', 'normal')
  doc.text(`${order.sku || 'SKU-UNKNOWN'}`, 15, 115)
  doc.text(`Weight: ${order.weight || '2.0'} kg`, 120, 115)
  doc.text('Qty: 1', 170, 115)

  doc.line(15, 120, 195, 120)

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by Bluewud OTS - Industrial Grade Logistics Suite', 15, 280)
  doc.text(`Printed on ${new Date().toLocaleString('en-IN')}`, 15, 285)

  // Save the PDF
  doc.save(`PackingSlip_${order.id}.pdf`)
}

/**
 * Generates a thermal-style shipping label (4x6 format).
 * @param {Object} order - The order data object.
 */
export const generateShippingLabel = (order) => {
  // 4x6 inches = 101.6 x 152.4 mm
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: [101.6, 152.4],
  })

  // Border
  doc.setDrawColor(0)
  doc.setLineWidth(0.5)
  doc.rect(3, 3, 95.6, 146.4)

  // Header
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('BLUEWUD', 10, 15)

  // Barcode area (simulated)
  doc.setFillColor(0, 0, 0)
  for (let i = 0; i < 30; i++) {
    const width = Math.random() > 0.5 ? 2 : 1
    doc.rect(10 + i * 2.5, 25, width, 20, 'F')
  }
  doc.setFontSize(8)
  doc.text(order.id, 10, 50)

  // Ship To
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('SHIP TO:', 10, 65)

  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text(`${order.customer || 'Customer'}`, 10, 75)
  doc.text(`${order.city || 'City'}`, 10, 83)
  doc.text(`${order.state || 'State'}`, 10, 91)

  // Weight
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(`${order.weight || '2.0'} KG`, 60, 130)

  doc.save(`Label_${order.id}.pdf`)
}
