/**
 * Label Generator Utility
 * Comprehensive support for generating shipping labels, packing slips, 
 * and manifests. Supports both local PDF generation and Carrier API integration.
 */

import { jsPDF } from 'jspdf';
import { sanitizeInput } from './dataUtils';

const CARRIER_CONFIGS = {
    delhivery: {
        apiUrl: 'https://track.delhivery.com/api/shipments',
        authHeader: 'X-Delhivery-Auth',
        timeout: 30000
    },
    bluedart: {
        apiUrl: 'https://track.bluedart.com/api',
        authHeader: 'Authorization',
        timeout: 30000
    },
    xpressbees: {
        apiUrl: 'https://api.xpressbees.com/shipments',
        authHeader: 'Authorization',
        timeout: 30000
    }
};

/**
 * Generates a professional packing slip PDF for an order.
 */
export const generatePackingSlip = (order) => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(22, 22, 26);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Bluewud OTS', 15, 25);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Packing Slip', 160, 25);

    // Order Details Section
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('ORDER DETAILS', 15, 55);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Order ID: ${order.id}`, 15, 65);
    doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 15, 72);
    doc.text(`Status: ${order.status}`, 15, 79);

    // Customer Details
    doc.setFont('helvetica', 'bold');
    doc.text('SHIP TO', 120, 55);

    doc.setFont('helvetica', 'normal');
    doc.text(`${order.customer || order.customerName || 'Customer'}`, 120, 65);
    doc.text(`${order.city || 'City'}, ${order.state || 'State'}`, 120, 72);

    // SKU Line Item Table
    doc.setFont('helvetica', 'bold');
    doc.text('ITEMS', 15, 100);

    doc.setDrawColor(200, 200, 200);
    doc.line(15, 105, 195, 105);

    doc.setFont('helvetica', 'normal');
    doc.text(`${order.sku || 'SKU-UNKNOWN'}`, 15, 115);
    doc.text(`Weight: ${order.weight || '2.0'} kg`, 120, 115);
    doc.text(`Qty: ${order.quantity || 1}`, 170, 115);

    doc.line(15, 120, 195, 120);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Bluewud OTS - Industrial Grade Logistics Suite', 15, 280);
    doc.text(`Printed on ${new Date().toLocaleString('en-IN')}`, 15, 285);

    doc.save(`PackingSlip_${order.id}.pdf`);
};

/**
 * Generates an internal shipping label (4x6 format) as fallback.
 */
export const generateInternalLabel = (order) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: [101.6, 152.4]
    });

    doc.setDrawColor(0);
    doc.setLineWidth(0.5);
    doc.rect(3, 3, 95.6, 146.4);

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('BLUEWUD', 10, 15);

    // Barcode area (simulated)
    doc.setFillColor(0, 0, 0);
    for (let i = 0; i < 30; i++) {
        const width = Math.random() > 0.5 ? 2 : 1;
        doc.rect(10 + i * 2.5, 25, width, 20, 'F');
    }
    doc.setFontSize(8);
    doc.text(order.id, 10, 50);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('SHIP TO:', 10, 65);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`${order.customer || order.customerName || 'Customer'}`, 10, 75);
    doc.text(`${order.city || 'City'}`, 10, 83);
    doc.text(`${order.state || 'State'} - ${order.pincode || ''}`, 10, 91);

    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(`${order.weight || '2.0'} KG`, 60, 130);

    doc.save(`InternalLabel_${order.id}.pdf`);
};

/**
 * Carrier API Integration for Real Labels
 */
export const generateCarrierLabel = async (order, carrier = 'delhivery') => {
    try {
        const config = CARRIER_CONFIGS[carrier.toLowerCase()];
        if (!config) throw new Error(`Unsupported carrier: ${carrier}`);

        const response = await fetch(config.apiUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                [config.authHeader]: import.meta.env[`VITE_${carrier.toUpperCase()}_TOKEN`] || ''
            },
            body: JSON.stringify({
                order_id: order.id,
                recipient: order.customerName,
                phone: order.phone,
                address: `${order.address}, ${order.city}, ${order.state} ${order.pincode}`,
                weight: order.weight,
                sku: order.sku
            })
        });

        const data = await response.json();
        if (!response.ok) throw new Error(data.message || 'Carrier API Failure');

        return { success: true, trackingId: data.tracking_id, labelUrl: data.pdf_url };
    } catch (err) {
        console.warn(`[Carrier API] Failed for ${carrier}, falling back to internal label.`);
        generateInternalLabel(order);
        return { success: false, error: err.message };
    }
};

// Aliases for backward compatibility
export const generateShippingLabel = (order) => generateInternalLabel(order);

export default {
    generatePackingSlip,
    generateInternalLabel,
    generateShippingLabel,
    generateCarrierLabel
};
